import {Expansion} from "./expansion";
import {MarketCard} from "./market-card";
import {MarketCardType} from "./martet-card-type";

export const WAR_ETERNAL_CARDS: MarketCard[] = [
    {
        name: "Bloodstone Jewel",
        type: MarketCardType.Gem,
        cost: 6,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Breach Ore",
        type: MarketCardType.Gem,
        cost: 4,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Dread Diamond",
        type: MarketCardType.Gem,
        cost: 3,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Erratic Ingot",
        type: MarketCardType.Gem,
        cost: 5,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Frozen Magmite",
        type: MarketCardType.Gem,
        cost: 3,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Scoria Slag",
        type: MarketCardType.Gem,
        cost: 4,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Volcanic Glass",
        type: MarketCardType.Gem,
        cost: 3,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Cairn Compass",
        type: MarketCardType.Relic,
        cost: 4,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Conclave Scroll",
        type: MarketCardType.Relic,
        cost: 3,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Fiend Catcher",
        type: MarketCardType.Relic,
        cost: 3,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Mage's Totem",
        type: MarketCardType.Relic,
        cost: 2,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Primordial Fetish",
        type: MarketCardType.Relic,
        cost: 4,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Vortex Gauntlet",
        type: MarketCardType.Relic,
        cost: 6,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Aurora",
        type: MarketCardType.Spell,
        cost: 5,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Carbonize",
        type: MarketCardType.Spell,
        cost: 4,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Conjure The Lost",
        type: MarketCardType.Spell,
        cost: 6,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Celestial Spire",
        type: MarketCardType.Spell,
        cost: 5,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Convection Field",
        type: MarketCardType.Spell,
        cost: 5,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Crystallize",
        type: MarketCardType.Spell,
        cost: 8,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Equilibrium",
        type: MarketCardType.Spell,
        cost: 7,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Fiery Torrent",
        type: MarketCardType.Spell,
        cost: 5,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Jagged Lightning",
        type: MarketCardType.Spell,
        cost: 4,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Kindle",
        type: MarketCardType.Spell,
        cost: 4,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Nova Forge",
        type: MarketCardType.Spell,
        cost: 6,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Pyrotechnic Surge",
        type: MarketCardType.Spell,
        cost: 4,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Reduce to Ash",
        type: MarketCardType.Spell,
        cost: 7,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Thoughtform Familiar",
        type: MarketCardType.Spell,
        cost: 3,
        expansion: Expansion.WarEternal,
    },
    {
        name: "Fossilized Scarab",
        type: MarketCardType.Gem,
        cost: 3,
        expansion: Expansion.TheVoid,
    },
    {
        name: "Dimensional Key",
        type: MarketCardType.Relic,
        cost: 8,
        expansion: Expansion.TheVoid,
    },
    {
        name: "Eternity Charm",
        type: MarketCardType.Relic,
        cost: 3,
        expansion: Expansion.TheVoid,
    },
    {
        name: "Resonate",
        type: MarketCardType.Spell,
        cost: 6,
        expansion: Expansion.TheVoid,
    },
    {
        name: "Conflagration",
        type: MarketCardType.Spell,
        cost: 3,
        expansion: Expansion.TheVoid,
    },
    {
        name: "Fulminate",
        type: MarketCardType.Spell,
        cost: 5,
        expansion: Expansion.TheVoid,
    },
    {
        name: "Inner Fire",
        type: MarketCardType.Spell,
        cost: 2,
        expansion: Expansion.TheVoid,
    },
    {
        name: "Thermal Dart",
        type: MarketCardType.Spell,
        cost: 4,
        expansion: Expansion.TheVoid,
    },
    {
        name: "Alien Element",
        type: MarketCardType.Gem,
        cost: 4,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Haunted Berylite",
        type: MarketCardType.Gem,
        cost: 3,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Pain Stone",
        type: MarketCardType.Gem,
        cost: 6,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Astral Cube",
        type: MarketCardType.Relic,
        cost: 5,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Riddlesphere",
        type: MarketCardType.Relic,
        cost: 3,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Char",
        type: MarketCardType.Spell,
        cost: 8,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Catalyst",
        type: MarketCardType.Spell,
        cost: 6,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Feedback Aura",
        type: MarketCardType.Spell,
        cost: 5,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Nether Conduit",
        type: MarketCardType.Spell,
        cost: 7,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Pyromancy",
        type: MarketCardType.Spell,
        cost: 7,
        expansion: Expansion.TheOuterDark,
    },
    {
        name: "Scorch",
        type: MarketCardType.Spell,
        cost: 5,
        expansion: Expansion.TheOuterDark,
    },
];