# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    cd aeons-end
    npm install -g npm
    npm install -g @angular/cli
    npm ci
    npm run-script build
  displayName: 'npm install'

- script: |
    npm run-script build
  displayName: 'build prod'
